data:
  project_root: "/work/jl1401/icl_protein_disease"
  data_dir: "data/data/Original_extracted/Original/data"
  binary_csv: "binary_csv.gz"
  processed_dir: "processed_data_c"

  train_diseases:
    - "C44"
    - "C809"
    - "C50"
    - "C61"

  test_diseases:
    - "C34"
    - "C18"
    - "C43"
    - "C53"
    - "C54"

  sample_n_per_disease: null

features:
  method: "none"
  n_features: 2941
  strategy: "none"

context:
  context_size: 32
  n_shot_test: 32

seed: 42
